version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - GRPC_ADDRESS=0.0.0.0:8080
      - HTTP_ADDRESS=0.0.0.0:8081
      - POSTGRES_CONN=postgresql://postgres:secret@postgres:5432/db
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
      - 8081:8081

  agent_1:
    image: agent
    environment:
      - ORCHESTRATOR_ADDRESS=orchestrator:8080
      - MAX_THREADS=10
    depends_on:
      - orchestrator

volumes:
  pgadmin_data:
  pg_data:
